import {
  haroldlibrary,
  kibbitznest,
  kibbitznest1,
  kibbitznest2,
  drawingroom,
  placeholder,
} from "../assets/images";

import {
  wifi,
  bathroom,
  noise,
  music,
  outlet,
  food,
  coffee,
  seat,
  couch,
  busy,
} from "../assets/icons";

export const NavLinks = [
  { href: "#home", label: "Home" },
  { href: "#about", label: "About" },
  { href: "#locations", label: "Locations" },
  { href: "#contact", label: "Contact" },
];

export const TopLocations = [
  {
    id: "01",
    name: "Harold Washington Library",
    address: "400 S State St, Chicago, IL 60605",
    description:
      "Sometimes a quiet study place isn't a necessity. Sometimes studying in a unique and creative environment is the best way to work and get the creative juices flowing. Kibbitznest is a perfect study location for those who want to get out of the usual quiet study and work spaces. Located in Clybourn, Kibbitznest is known for its unique combination of bookstore, cafe, and bar, providing a cozy and inviting atmosphere for visitors to enjoy books, coffee, and cocktails. It has many seats and tables as well as lounge chairs and sofas to work on. You will be surrounded by other people engaging in conversation with alcoholic beverages or coffee in hand. There are also a lot of people playing board games or card games. If a loud and busy atmosphere doesn't distract your workflow, you need to check this place out!",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "4:00 PM - 11:00 PM" },
      { day: "Thursday", hours: "4:00 PM - 11:00 PM" },
      { day: "Friday", hours: "4:00 PM - 12:00 AM" },
      { day: "Saturday", hours: "1:00 PM - 12:00 AM" },
      { day: "Sunday", hours: "1:00 PM - 7:00 PM" },
    ],
    details: [
      { attr: "Wifi", value: "None", src: wifi },
      { attr: "Bathrooms", value: "Yes", src: bathroom },
      { attr: "Noise", value: "Loud", src: noise },
      { attr: "Music", value: "Yes", src: music },
      { attr: "Outlets", value: "Many", src: outlet },
      { attr: "Food", value: "Yes", src: food },
      { attr: "Coffee", value: "Yes", src: coffee },
      { attr: "Seating", value: "Many", src: seat },
      { attr: "Couches", value: "Yes", src: couch },
      { attr: "Busy", value: "Yes", src: busy },
    ],
    images: [haroldlibrary],
  },
  {
    id: "02",
    name: "Kibbitznest",
    address: "2212 N Clybourn Ave, Chicago, IL 60614",
    description:
      "Sometimes a quiet study place isn't a necessity. Sometimes studying in a unique and creative environment is the best way to work and get the creative juices flowing. Kibbitznest is a perfect study location for those who want to get out of the usual quiet study and work spaces. Located in Clybourn, Kibbitznest is known for its unique combination of bookstore, cafe, and bar, providing a cozy and inviting atmosphere for visitors to enjoy books, coffee, and cocktails. It has many seats and tables as well as lounge chairs and sofas to work on. You will be surrounded by other people engaging in conversation with alcoholic beverages or coffee in hand. There are also a lot of people playing board games or card games. If a loud and busy atmosphere doesn't distract your workflow, you need to check this place out!",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "4:00 PM - 11:00 PM" },
      { day: "Thursday", hours: "4:00 PM - 11:00 PM" },
      { day: "Friday", hours: "4:00 PM - 12:00 AM" },
      { day: "Saturday", hours: "1:00 PM - 12:00 AM" },
      { day: "Sunday", hours: "1:00 PM - 7:00 PM" },
    ],
    details: [
      { attr: "Wifi", value: "None", src: wifi },
      { attr: "Bathrooms", value: "Yes", src: bathroom },
      { attr: "Noise", value: "Loud", src: noise },
      { attr: "Music", value: "Yes", src: music },
      { attr: "Outlets", value: "Many", src: outlet },
      { attr: "Food", value: "Yes", src: food },
      { attr: "Coffee", value: "Yes", src: coffee },
      { attr: "Seating", value: "Many", src: seat },
      { attr: "Couches", value: "Yes", src: couch },
      { attr: "Busy", value: "Yes", src: busy },
    ],
    rating: { rating: 4.5, desc: "Great Location" },
    images: [kibbitznest, kibbitznest1, kibbitznest2],
  },
  {
    id: "03",
    name: "Drawing Room",
    address: "12 S Michigan Ave, Chicago, IL 60603",
    description:
      "Sometimes a quiet study place isn't a necessity. Sometimes studying in a unique and creative environment is the best way to work and get the creative juices flowing. Kibbitznest is a perfect study location for those who want to get out of the usual quiet study and work spaces. Located in Clybourn, Kibbitznest is known for its unique combination of bookstore, cafe, and bar, providing a cozy and inviting atmosphere for visitors to enjoy books, coffee, and cocktails. It has many seats and tables as well as lounge chairs and sofas to work on. You will be surrounded by other people engaging in conversation with alcoholic beverages or coffee in hand. There are also a lot of people playing board games or card games. If a loud and busy atmosphere doesn't distract your workflow, you need to check this place out!",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "4:00 PM - 11:00 PM" },
      { day: "Thursday", hours: "4:00 PM - 11:00 PM" },
      { day: "Friday", hours: "4:00 PM - 12:00 AM" },
      { day: "Saturday", hours: "1:00 PM - 12:00 AM" },
      { day: "Sunday", hours: "1:00 PM - 7:00 PM" },
    ],
    details: [
      { attr: "Wifi", value: "None", src: wifi },
      { attr: "Bathrooms", value: "Yes", src: bathroom },
      { attr: "Noise", value: "Loud", src: noise },
      { attr: "Music", value: "Yes", src: music },
      { attr: "Outlets", value: "Many", src: outlet },
      { attr: "Food", value: "Yes", src: food },
      { attr: "Coffee", value: "Yes", src: coffee },
      { attr: "Seating", value: "Many", src: seat },
      { attr: "Couches", value: "Yes", src: couch },
      { attr: "Busy", value: "Yes", src: busy },
    ],
    images: [drawingroom],
  },
  {
    id: "04",
    name: "Placeholder",
    address: "1234 Somewhere St, Chicago, IL 60603",
    description:
      "Sometimes a quiet study place isn't a necessity. Sometimes studying in a unique and creative environment is the best way to work and get the creative juices flowing. Kibbitznest is a perfect study location for those who want to get out of the usual quiet study and work spaces. Located in Clybourn, Kibbitznest is known for its unique combination of bookstore, cafe, and bar, providing a cozy and inviting atmosphere for visitors to enjoy books, coffee, and cocktails. It has many seats and tables as well as lounge chairs and sofas to work on. You will be surrounded by other people engaging in conversation with alcoholic beverages or coffee in hand. There are also a lot of people playing board games or card games. If a loud and busy atmosphere doesn't distract your workflow, you need to check this place out!",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "4:00 PM - 11:00 PM" },
      { day: "Thursday", hours: "4:00 PM - 11:00 PM" },
      { day: "Friday", hours: "4:00 PM - 12:00 AM" },
      { day: "Saturday", hours: "1:00 PM - 12:00 AM" },
      { day: "Sunday", hours: "1:00 PM - 7:00 PM" },
    ],
    details: [
      { attr: "Wifi", value: "None", src: wifi },
      { attr: "Bathrooms", value: "Yes", src: bathroom },
      { attr: "Noise", value: "Loud", src: noise },
      { attr: "Music", value: "Yes", src: music },
      { attr: "Outlets", value: "Many", src: outlet },
      { attr: "Food", value: "Yes", src: food },
      { attr: "Coffee", value: "Yes", src: coffee },
      { attr: "Seating", value: "Many", src: seat },
      { attr: "Couches", value: "Yes", src: couch },
      { attr: "Busy", value: "Yes", src: busy },
    ],
    images: [placeholder],
  },
];
